#!/bin/bash

dev_id=$(xinput | rg -i "touchpad.+id=(\d+)" -or '$1')
state=$(xinput --list-props ${dev_id} | rg "Device Enabled.*:.*(\d+)" -or '$1')

echo ${state}
if [[ ${state} -eq 1 ]]; then
    xinput disable ${dev_id}
else
    xinput enable ${dev_id}
fi
