require('user.core.mappings')
require('user.core.options')
require('user.core.colorscheme')

require('user.plugins-setup')
require('user.plugins.mason')
require('user.plugins.nvim-cmp')
require('user.plugins.lspconfig')
require('user.plugins.nvim-dap')
require('user.plugins.nvim-dapui')
require('user.plugins.lualine')
require('user.plugins.telescope')
require('user.plugins.indent-blankline')
require('user.plugins.nvim-autopairs')
require('user.plugins.nvim-gomove')
require('user.plugins.bufdelete')
